### ISSUE TITLE
The result is different from that in manual

### ISSUE THREAD

**Issue by NeilChangYanpeng** [wt-hu/pyCausalFS#2]
Hi, @wt-hu 
I ran example_MB.py located in "/CBD/example" and I found the result is different from that in manual, as you can see in the following pics:
![图片](https://user-images.githubusercontent.com/41663460/100715685-81570c80-33f2-11eb-9d0f-a2343a487bf9.png)
![图片](https://user-images.githubusercontent.com/41663460/100715784-ad728d80-33f2-11eb-96b8-9288fa29eb50.png)

I am confused why they are different, could you give me some explanations?
Thank you in advance!

**Comment by wt-hu** [comment]
Well, this issue, we have explained in the UPDATELOG. 
Recently, We have replaced the conditional independence (CI) test from Chi^2 test to G^2 test, due to the poor performance of the Chi^2 test on some BN datasets. If the test results are different from the illustrations in the manual, the actual test results shall prevail. 
We will update our manual next.

**Comment by NeilChangYanpeng** [comment]
Thank you for your reply.
